### ISSUE TITLE
Introduce proper abstraction for the Step runs within a Step

### ISSUE THREAD

**Issue by tachyons** [tramlinehq/tramline#100]
As per our current data modelling, each train can have multiple train runs (AKA releases) and steps. A step_run refers to the execution of train run for the given step for given commit. Ie there is no proper abstraction train run per step. This makes storing approval status complicated. Current workaround is to use `sign_required` column, but it is a clear smell of missing abstraction

**Comment by nid90** [comment]
With the introduction of `Build` and `Submission` as domain models in the [V2](https://github.com/tramlinehq/tramline/pull/633), the need for this abstraction disappears.
