### ISSUE TITLE
User should be able to modify the next version name that will be used by Tramline while creating a release

### ISSUE THREAD

**Issue by pratul** [tramlinehq/tramline#172]
For ex: if the last release was version 8.2.2, tramline will automatically use the 8.3.* series for the next release. However, it is possible that the user may want the next release to use 9.0.*. 

We should have a workflow for this. 

## "Start new release" with dropdown
One way to do this could be to show the next version name on the Start New Release button -- we change the button to say "Start New Release: 9.4.*". 

Then, we add a little dropdown next to the button which says "Change next version number" which allows people to enter anything else apart from 9.4.*, which means they can enter 9.5.0 or even 12.0.0.

**Comment by nid90** [comment]
This was partly done in #458 which supports major and minor version bumps when starting a release.
