### ISSUE TITLE
Reconsider launching all steps when a new commit lands

### ISSUE THREAD

**Issue by kitallis** [tramlinehq/tramline#207]
We've currently done this because it's a good idea from a sanity point of view to ensure previous stakeholders of a previously run step get an updated build at the landing of a new commit.

But from a PoV of a tester / QA, this is an overreach. Since if the new commit that has landed is itself buggy, they should be able to check that earlier than finding out in a later step. In other words, we should consider asking for the sign-off again on each step when a new commit lands.

**Comment by nid90** [comment]
We have added a configuration for this in #536.
