### ISSUE TITLE
Automatic and scheduled release trains 

### ISSUE THREAD

**Issue by pratul** [tramlinehq/tramline#280]
Lots can be done here, for e.g. 
- schedule releases to start automatically 
- preset template for staged rollout on play store 
- automatic notifications to suggest teams to start a new release 
- and more?

**Comment by kitallis** [comment]
- [ ] Only for almost trunk
- [ ] Only if there are changes
- [ ] Only if the last release is completed or stopped
- [ ] Send a notification pre-release
- [ ] Warnings for manual release if automatic
