### ISSUE TITLE
Reset password is broken

### ISSUE THREAD

**Issue by tachyons** [tramlinehq/tramline#411]
## Problem

The password reset page is not working as intented

## Steps to Reproduce

Steps to reproduce the behaviour (for eg.):

1. Go to login page
2. Click on forgot password
3. Enter email
4. Click on the password reset link on the email

## Expected behaviour

It allows to change password

**Comment by kitallis** [comment]
Thanks for filing @tachyons! We've addressed this in #412. Should be merged shortly.

**Comment by kitallis** [comment]
@tachyons This is fixed, let me know if find any other problems. I'll close this issue once you ack.

**Comment by tachyons** [comment]
Issue is now resolved
