### ISSUE TITLE
Deprecate Slack as a distribution channel

### ISSUE THREAD

**Issue by kitallis** [tramlinehq/tramline#448]
## Proposal

In our chats with users, it seems like it's not clear what the difference between Slack notifications and Slack as a distribution channel is. It feels like we can get rid of Slack as a distribution channel altogether and have the Notification channel handle all the distribution responsibilities as well

## What this achieves / problem(s) it solves 

Slack / Email as notification channels can also solve the artifact distribution problem. We don't need to have them explicitly as distribution channels also. Doing this should make the system much simpler to understand.

Also see https://github.com/tramlinehq/tramline/issues/447

**Comment by nid90** [comment]
This is done as part of Product V2 - https://github.com/tramlinehq/tramline/pull/633
