### ISSUE TITLE
Validations and automations for Almost Trunk branching strategy

### ISSUE THREAD

**Issue by pratul** [tramlinehq/tramline#88]
### Choosing commits 

1. User marks a commit message
... and we automatically cherry pick that commit onto the release branch of the live release. 

2. User picks commits from a list populated from the working branch
... and we cherry pick that commit onto the release branch

### Direction of copy 

1. Commit lands on release branch and is cherry picked onto the working branch 

1. Commit lands on working branch and is cherry picked onto the release branch 

## Questions
- which one of the two approaches is simpler to implement? better for the user? 
- how will failures be handled? 

## Notes
Handle stopping release with a warning if a diff exists between the release and working branch. Also, do the same for other branching strategies.

**Comment by nid90** [comment]
We chose to do backmerges from the release branch to the working branch in #531.
